# Generated by Django 5.2.6 on 2025-09-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_age_limit_job_application_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='more_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobVacancyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vacancy_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_images', to='jobs.job')),
            ],
        ),
    ]
